COLOUR_SOURCE = "RAW" 		# get colour from "JPG" or "RAW"

#Detecting
MIN_THRESHOLD = 160
MAX_THRESHOLD = 255
MIN_NUM_PIXELS = 7
MAX_NUM_PIXELS = 30
MIN_CIRCULARITY = 0.3

MIN_SURROUNDING_CONTRAST = 50

#Pairing
MAX_ANGLE = 30
AVG_RADIUS_MULTIPLIER = 50
MIN_RADIUS_RATIO = 0.5